### ISSUE TITLE
Create acount

### ISSUE THREAD

**Issue by DaltonEsc** [Bluepuff71/TTU-Stuff#6]
Tried to break each step of creating an account. At the card step i just punched in a too small number hit 55445. Threw 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 4, end 8, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at project.CustomerInterface.createAccount(CustomerInterface.java:325)
	at project.CustomerInterface.createAccount(CustomerInterface.java:347)
	at project.CustomerInterface.createAccount(CustomerInterface.java:347)
	at project.CustomerInterface.createAccount(CustomerInterface.java:347)
	at project.CustomerInterface.createAccount(CustomerInterface.java:347)
	at project.CustomerInterface.initialMenu(CustomerInterface.java:51)
	at runner.Runner.main(Runner.java:70)

**Comment by Bluepuff71** [comment]
Fixed! I pushed the fix to the master branch!
